#!/bin/sh
feh --bg-fill --no-fehbg $WALLPAPER &
emacs --daemon &
setxkbmap -option caps:swapescape &
xrdb -load ~/.config/x11/xdefaults &
numlockx &
sxhkd &
urxvtd -q -o &
USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
exec herbstluftwm --locked
