#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

#killsplit() {
#	res=$(hc layout | awk '/FOCUS/ {print $3}');
#	hc remove;
#	hc close $res;
#}

hc emit_hook reload

hc set_layout grid

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier

# I finally managed to set frame layout to grid 
# on all tags and frames as per:
# https://herbstluftwm.org/faq.html#_q_i_set_default_frame_layout_to_my_favorite_layout_but_it_doesn_8217_t_work_with_the_root_frame_existing_frames
hc set default_frame_layout grid
hc substitute ALGO settings.default_frame_layout \
	foreach T tags.by-name \
		sprintf ATTR '%c.tiling.root.algorithm' T \
		set_attr ATTR ALGO
#hc set layout grid
hc keybind $Mod-Shift-r reload
hc keybind $Mod-F1 spawn $TERMINAL -e alsamixer
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-Shift-s spawn skypeforlinux
hc keybind $Mod-q close
hc keybind $Mod-r remove
hc keybind $Mod-Return spawn $TERMINAL
hc keybind $Mod-Shift-Return spawn xterm
hc keybind $Mod-b spawn $BROWSER
hc keybind $Mod-Shift-b spawn firefox
hc keybind $Mod-d spawn dmenu_run -b -l 10 -fn "Hack Regular Nerd Font Complete"
hc keybind $Mod-f spawn $TERMINAL -e lf
hc keybind $Mod-Shift-f spawn pcmanfm
# uni keybindings
hc keybind $Mod-p spawn keepassxc
hc keybind $Mod-t spawn teams

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-y	split	left	0.5
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-i	split	top	0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-s floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-Control-f set_attr clients.focus.floating toggle
#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# the first layout after the second / is the default one
#horizontal max vertical grid    

hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal vertical max grid             \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
# hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
# nie wiem czy to ma jakies znaczenie i tak dalej
# hc set frame_bg_active_color '#345F0C'
# also setting setting the variable below got rid of this dreary like line
# now there are not visible borders which is very good
# apparently uncommenting this lines fixed something but I have no idea why
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
# so by setting the below variable to zero I managed to
# like whatever get rid of the dreary thing set on line 139 (this colour 345F0C)
# still not perfect but better also look (x)
# after relogging day later something broke so whatever
hc set frame_transparent_width 0
hc set frame_gap 4

# dracula active window border
hc attr theme.active.color '#50fa7b'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set frame_active_opacity 1
hc set frame_normal_opacity 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# the line below is broken now
#hc set_monitors 1600x865+0+35
# or simply:
hc detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
panel="$XDG_CONFIG_HOME"/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
   ## start it on each monitor
   "$panel" "$monitor" &
done
